[book]
authors = ["Shiguredo Inc."]
language = "ja"
multilingual = false
src = "src"
title = "Sora Labo ドキュメント"

[output.html]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js"]

[output.html.search]
enable = true
